### ISSUE TITLE
Dataset Format Question

### ISSUE THREAD

**Issue by happywt** [ChakiCurtin/INSBench#2]
Author Hello, thank you for your answer last time. I successfully trained on the MoNuSeg dataset and got the results.
This time I want to ask you a few questions. First, how did you get the MoNuSeg dataset in yolo format? Did you use other datasets to convert to yolo? Second, I wanted to train on other datasets such as cpm17 and CoNSep with INSBench, but these datasets don't have annotations in yolo format, so it was a bit difficult for me. I mainly wanted to ask how you obtained the yolo format data set of MoNuSeg, and see if you could give me some inspiration to get the yolo format annotation of cpm17 and CoNSep data set.
Your reply is very useful to me, thank you.

**Comment by chasercodeio** [comment]
Hi @happywt, good to hear MoNuSeg trained well. Regarding the Yolo format, when downloading the original MoNuSeg dataset, it comes with XML format for its annotations. Then, it is simply converting the values per nucleus to yolo darknet format. For more information, I will link the [CNSBench repository](https://github.com/SickMcNugget/CNSBench/tree/main). That repository looks into training semantic segmentation models. For your use (annotations), Specifically, look at the file [CNSBench/dataset.py](https://github.com/SickMcNugget/CNSBench/blob/main/cnsbench/datasets.py). It has the code required for converting from XML format to yolo (have a read of the full file however, some parts maybe more useful such as line 360 function yolofy).
While I am not fully aware of the process of converting it as it has been a while since I have looked into it and my friend is the one who coded that up, it should be quite straightforward and you should be able to create a conversion file for cpm17 and CoNSep.
Regarding other datasets that have been used, that repository also creates yolo annotations for MoNuSAC, TNBC and CryoNuSeg.
